---
application:
  name: "transcriber"
  project: "transcriber"
  organization: "QoveryCommunity"
routers:
- name: "main-transcriber"
  routes:
  - application_name: "transcriber"
    paths:
    - "/*"
